apiVersion: v1
kind: Service
metadata:
  name: {{ include "rfc2136-gateway.fullname" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  selector:
    app: {{ include "rfc2136-gateway.name" . }}
  ports:
    - name: tcp-53
      port: {{ .Values.service.ports.tcp }}
      targetPort: tcp-53
      protocol: TCP
    - name: udp-53
      port: {{ .Values.service.ports.udp }}
      targetPort: udp-53
      protocol: UDP
